# Site settings
author: Sandie Nunez
title: Sandie Soars
header-img: img/home-bg.png
email: snunez@vt.edu
copyright_name: Sandie Nunez
description: > # this means to ignore newlines until "baseurl:"
  A Journey from Biologist to Coder
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sandienunez

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
